In [1]:
import csv
import pandas as pd

# Function to display inventory
def view_inventory():
    with open('item.csv', 'r') as file:
        print("Inventory:")
        print(file.read())

# Function to display inventory as CSV in Jupyter Notebook
def view_inventory_csv():
    inventory_data = []
    with open('item.csv', 'r') as file:
        inventory = csv.reader(file)
        for item in inventory:
            inventory_data.append(item)

    df = pd.DataFrame(inventory_data, columns=["Item Number", "Item Name", "Quantity", "Price"])
    display(df)

# Function to upload items to inventory
def upload_items():
    with open('item.csv', 'a') as file:
        item_number = input("Enter item number: ")
        item_name = input("Enter item name: ")
        quantity = input("Enter quantity: ")
        price = input("Enter price: ")
        file.write(f"{item_number},{item_name},{quantity},{price}\n")
    print("Item uploaded successfully.")

# Function to add items to cart
def add_to_cart():
    cart = []
    with open('item.csv', 'r') as file:
        inventory = csv.reader(file)
        for item in inventory:
            print(f"Item: {item[1]}, Price: {item[3]}")

    while True:
        item_name = input("Enter the name of the item you want to add to your cart (or 'done' to finish): ")
        if item_name.lower() == 'done':
            break
        quantity = input("Enter the quantity: ")
        cart.append((item_name, quantity))
    return cart

# Function to generate bill
def generate_bill(cart):
    total_price = 0
    print("Your Bill:")
    print("Item\t\tQuantity\tPrice")
    for item, quantity in cart:
        with open('item.csv', 'r') as file:
            inventory = csv.reader(file)
            for row in inventory:
                if row[1] == item:
                    price = float(row[3]) * int(quantity)
                    total_price += price
                    print(f"{item}{quantity}{price}")
    print(f"Total Price: {total_price}")

# Main function
def main():
    while True:
        print("\n1. User")
        print("2. Customer")
        print("3. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            while True:
                print("\n1. View Inventory")
                print("2. Upload Items")
                print("3. Exit")
                user_choice = input("Enter your choice: ")

                if user_choice == '1':
                    view_inventory()
                elif user_choice == '2':
                    upload_items()
                elif user_choice == '3':
                    break
                else:
                    print("Invalid choice. Please try again.")

        elif choice == '2':
            while True:
                print("\n1. View Inventory")
                print("2. Add to Cart")
                print("3. Generate Bill")
                print("4. Exit")
                customer_choice = input("Enter your choice: ")

                if customer_choice == '1':
                    view_inventory_csv()
                elif customer_choice == '2':
                    cart = add_to_cart()
                elif customer_choice == '3':
                    generate_bill(cart)
                elif customer_choice == '4':
                    break
                else:
                    print("Invalid choice. Please try again.")

        elif choice == '3':
            print("Exiting the program. Goodbye!")
            break

        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

1. User
2. Customer
3. Exit
Enter your choice: 1

1. View Inventory
2. Upload Items
3. Exit
Enter your choice: 1
Inventory:
code,name,price,quantity
1,Milk,30,20
2,Ball,25.0,12
3,Ribbon,20.0,23
4,Oreo,10,20
5,Jim jam,20,10
6,Apple,38,500
7,Mango,4,70
8,Mug,45,120
9,Maggi,42,123


1. View Inventory
2. Upload Items
3. Exit
Enter your choice: 2
Enter item number: 10
Enter item name: Chocos
Enter quantity: 12
Enter price: 190
Item uploaded successfully.

1. View Inventory
2. Upload Items
3. Exit
Enter your choice: 2
Enter item number: 11
Enter item name: Pasta
Enter quantity: 6
Enter price: 98
Item uploaded successfully.

1. View Inventory
2. Upload Items
3. Exit
Enter your choice: 2
Enter item number: 12
Enter item name: Ketchup
Enter quantity: 5
Enter price: 40
Item uploaded successfully.

1. View Inventory
2. Upload Items
3. Exit
Enter your choice: 1
Inventory:
code,name,price,quantity
1,Milk,30,20
2,Ball,25.0,12
3,Ribbon,20.0,23
4,Oreo,10,20
5,Jim jam,20,10
6,Apple,38,500
7,Mango,4,70
8,Mug,45,120
9,Maggi,42,123
10,Chocos,12,190
11,Pasta,6,98
12,Ketchup,5,40


1. View Inventory
2. Upload Items
3. Exit
Enter your choice: 3

1. User
2. Customer
3. Exit
Enter your choice: 2

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 1

   Item Number Item Name Quantity     Price
0         code      name    price  quantity
1            1      Milk       30        20
2            2      Ball     25.0        12
3            3    Ribbon     20.0        23
4            4      Oreo       10        20
5            5   Jim jam       20        10
6            6     Apple       38       500
7            7     Mango        4        70
8            8       Mug       45       120
9            9     Maggi       42       123
10          10    Chocos       12       190
11          11     Pasta        6        98
12          12   Ketchup        5        40

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 2
Item: name, Price: quantity
Item: Milk, Price: 20
Item: Ball, Price: 12
Item: Ribbon, Price: 23
Item: Oreo, Price: 20
Item: Jim jam, Price: 10
Item: Apple, Price: 500
Item: Mango, Price: 70
Item: Mug, Price: 120
Item: Maggi, Price: 123
Item: Chocos, Price: 190
Item: Pasta, Price: 98
Item: Ketchup, Price: 40
Enter the name of the item you want to add to your cart (or 'done' to finish): Pasta
Enter the quantity: 2
Enter the name of the item you want to add to your cart (or 'done' to finish): done

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 3
Your Bill:
Item		Quantity	Price
Pasta2196.0
Total Price: 196.0

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 2
Item: name, Price: quantity
Item: Milk, Price: 20
Item: Ball, Price: 12
Item: Ribbon, Price: 23
Item: Oreo, Price: 20
Item: Jim jam, Price: 10
Item: Apple, Price: 500
Item: Mango, Price: 70
Item: Mug, Price: 120
Item: Maggi, Price: 123
Item: Chocos, Price: 190
Item: Pasta, Price: 98
Item: Ketchup, Price: 40
Enter the name of the item you want to add to your cart (or 'done' to finish): Chocos
Enter the quantity: 4
Enter the name of the item you want to add to your cart (or 'done' to finish): Mug
Enter the quantity: 3
Enter the name of the item you want to add to your cart (or 'done' to finish): done

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 1

   Item Number Item Name Quantity     Price
0         code      name    price  quantity
1            1      Milk       30        20
2            2      Ball     25.0        12
3            3    Ribbon     20.0        23
4            4      Oreo       10        20
5            5   Jim jam       20        10
6            6     Apple       38       500
7            7     Mango        4        70
8            8       Mug       45       120
9            9     Maggi       42       123
10          10    Chocos       12       190
11          11     Pasta        6        98
12          12   Ketchup        5        40

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 3
Your Bill:
Item		Quantity	Price
Chocos4760.0
Mug3360.0
Total Price: 1120.0

1. View Inventory
2. Add to Cart
3. Generate Bill
4. Exit
Enter your choice: 4

1. User
2. Customer
3. Exit
Enter your choice: 3
Exiting the program. Goodbye!